local c = require('moonlight.palette')

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()

  -- Base highlights
  hl(0, "Normal", { fg = c.fg, bg = c.bg })
  hl(0, "SignColumn", { fg = c.fg, bg = c.bg })
  hl(0, "VertSplit", { fg = c.border, bg = c.bg })
  hl(0, "NormalFloat", { fg = c.fg, bg = c.float })
  hl(0, "FloatBorder", { fg = c.border, bg = c.float })
  hl(0, "ColorColumn", { fg = 'NONE', bg = c.active })
  hl(0, "Conceal", { fg = c.disabled, bg = 'NONE' })
  hl(0, "Cursor", { fg = c.cursor, bg = 'NONE', reverse = true })
  hl(0, "CursorIM", { fg = c.cursor, bg = 'NONE', reverse = true })
  hl(0, "lCursor", { fg = c.cursor, bg = 'NONE', reverse = true })
  hl(0, "TermCursor", { fg = c.cursor, bg = 'NONE', reverse = true })
  hl(0, "TermCursorNC", { fg = c.cursor, bg = 'NONE', reverse = true })
  hl(0, "Directory", { fg = c.blue, bg = 'NONE' })
  hl(0, "DiffAdd", { fg = c.green, bg = 'NONE', reverse = true })
  hl(0, "DiffChange", { fg = c.orange, bg = 'NONE', reverse = true })
  hl(0, "DiffDelete", { fg = c.red, bg = 'NONE', reverse = true })
  hl(0, "DiffText", { fg = c.yellow, bg = 'NONE', reverse = true })
  hl(0, "EndOfBuffer", { fg = c.disabled, bg = 'NONE' })
  hl(0, "ErrorMsg", { fg = c.error, bg = 'NONE' })
  hl(0, "Folded", { fg = c.disabled, bg = 'NONE', italic = true })
  hl(0, "FoldColumn", { fg = c.text, bg = 'NONE' })
  hl(0, "IncSearch", { fg = c.bg, bg = c.yellow })
  hl(0, "LineNr", { fg = c.line_numbers, bg = 'NONE' })
  hl(0, "CursorLineNr", { fg = c.accent, bg = 'NONE' })
  hl(0, "MatchParen", { fg = c.yellow, bg = 'NONE', bold = true })
  hl(0, "ModeMsg", { fg = c.accent, bg = 'NONE' })
  hl(0, "MoreMsg", { fg = c.accent, bg = 'NONE' })
  hl(0, "MsgSeparator", { fg = c.fg, bg = c.bg })
  hl(0, "MsgArea", { link = 'Normal' })
  hl(0, "NonText", { fg = c.disabled, bg = 'NONE' })
  hl(0, "Pmenu", { fg = c.text, bg = c.contrast })
  hl(0, "PmenuSel", { fg = c.accent, bg = c.active })
  hl(0, "PmenuSbar", { fg = c.text, bg = c.contrast })
  hl(0, "PmenuThumb", { fg = c.fg, bg = c.accent })
  hl(0, "Question", { fg = c.green, bg = 'NONE' })
  hl(0, "QuickFixLine", { fg = c.bg, bg = c.yellow })
  hl(0, "qfLineNr", { fg = c.yellow, bg = 'NONE' })
  hl(0, "Search", { fg = c.bg, bg = c.yellow })
  hl(0, "SpecialKey", { fg = c.purple, bg = 'NONE' })
  hl(0, "SpellBad", { fg = c.red, bg = 'NONE', italic = true, undercurl = true })
  hl(0, "SpellCap", { fg = c.blue, bg = 'NONE', italic = true, undercurl = true })
  hl(0, "SpellLocal", { fg = c.cyan, bg = 'NONE', italic = true, undercurl = true })
  hl(0, "SpellRare", { fg = c.purple, bg = 'NONE', italic = true, undercurl = true })
  hl(0, "StatusLine", { fg = c.fg, bg = c.contrast })
  hl(0, "StatusLineNC", { fg = c.text, bg = c.disabled })
  hl(0, "StatusLineTerm", { fg = c.fg, bg = c.contrast })
  hl(0, "StatusLineTermNC", { fg = c.text, bg = c.disabled })
  hl(0, "TabLineFill", { fg = c.fg, bg = 'NONE' })
  hl(0, "TabLineSel", { fg = c.bg, bg = c.accent })
  hl(0, "TabLine", { fg = c.fg, bg = 'NONE' })
  hl(0, "Title", { fg = c.green, bg = 'NONE', bold = true })
  hl(0, "Visual", { fg = 'NONE', bg = c.selection })
  hl(0, "VisualNOS", { fg = 'NONE', bg = c.selection })
  hl(0, "WarningMsg", { fg = c.yellow, bg = 'NONE' })
  hl(0, "WildMenu", { fg = c.orange, bg = 'NONE', bold = true })
  hl(0, "CursorColumn", { fg = 'NONE', bg = c.active })
  hl(0, "CursorLine", { fg = 'NONE', bg = 'NONE' })
  hl(0, "ToolbarLine", { fg = c.fg, bg = c.bg_alt })
  hl(0, "ToolbarButton", { fg = c.fg, bg = 'NONE', bold = true })
  hl(0, "NormalMode", { fg = c.accent, bg = 'NONE', reverse = true })
  hl(0, "InsertMode", { fg = c.green, bg = 'NONE', reverse = true })
  hl(0, "ReplaceMode", { fg = c.red, bg = 'NONE', reverse = true })
  hl(0, "VisualMode", { fg = c.purple, bg = 'NONE', reverse = true })
  hl(0, "CommandMode", { fg = c.text, bg = 'NONE', reverse = true })
  hl(0, "Warnings", { fg = c.yellow, bg = 'NONE' })

  -- Health
  hl(0, "healthError", { fg = c.error, bg = 'NONE' })
  hl(0, "healthSuccess", { fg = c.green, bg = 'NONE' })
  hl(0, "healthWarning", { fg = c.yellow, bg = 'NONE' })

  -- Syntax groups
  hl(0, "Comment", { fg = c.comments, bg = 'NONE', italic = true })
  hl(0, "Constant", { fg = c.yellow, bg = 'NONE' })
  hl(0, "String", { fg = c.green, bg = 'NONE', italic = true })
  hl(0, "Character", { fg = c.orange, bg = 'NONE' })
  hl(0, "Number", { fg = c.orange, bg = 'NONE' })
  hl(0, "Boolean", { fg = c.orange, bg = 'NONE' })
  hl(0, "Float", { fg = c.orange, bg = 'NONE' })
  hl(0, "Identifier", { fg = c.text, bg = 'NONE', italic = true })
  hl(0, "Function", { fg = c.blue, bg = 'NONE', italic = true })
  hl(0, "Statement", { fg = c.pink, bg = 'NONE' })
  hl(0, "Conditional", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "Repeat", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "Label", { fg = c.purple, bg = 'NONE' })
  hl(0, "Operator", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Keyword", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "Exception", { fg = c.cyan, bg = 'NONE' })
  hl(0, "PreProc", { fg = c.purple, bg = 'NONE' })
  hl(0, "Include", { fg = c.blue, bg = 'NONE' })
  hl(0, "Define", { fg = c.pink, bg = 'NONE' })
  hl(0, "Macro", { fg = c.cyan, bg = 'NONE' })
  hl(0, "PreCondit", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Type", { fg = c.purple, bg = 'NONE' })
  hl(0, "StorageClass", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Structure", { fg = c.purple, bg = 'NONE' })
  hl(0, "Typedef", { fg = c.red, bg = 'NONE' })
  hl(0, "Special", { fg = c.red, bg = 'NONE' })
  hl(0, "SpecialChar", { fg = c.pink, bg = 'NONE' })
  hl(0, "Tag", { fg = c.red, bg = 'NONE' })
  hl(0, "Delimiter", { fg = c.cyan, bg = 'NONE' })
  hl(0, "SpecialComment", { fg = c.text, bg = 'NONE' })
  hl(0, "Debug", { fg = c.red, bg = 'NONE' })
  hl(0, "Underlined", { fg = c.link, bg = 'NONE', underline = true })
  hl(0, "Ignore", { fg = c.disabled, bg = 'NONE' })
  hl(0, "Error", { fg = c.error, bg = 'NONE', bold = true, underline = true })
  hl(0, "Todo", { fg = c.yellow, bg = 'NONE', bold = true, italic = true })

  -- Markdown
  hl(0, "markdownBlockquote", { fg = c.green, bg = 'NONE' })
  hl(0, "markdownCode", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownCodeBlock", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownCodeDelimiter", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownH1", { fg = c.cyan, bg = 'NONE', bold = true })
  hl(0, "markdownH2", { fg = c.red, bg = 'NONE', bold = true })
  hl(0, "markdownH3", { fg = c.green, bg = 'NONE', bold = true })
  hl(0, "markdownH4", { fg = c.cyan, bg = 'NONE' })
  hl(0, "markdownH5", { fg = c.red, bg = 'NONE' })
  hl(0, "markdownH6", { fg = c.green, bg = 'NONE' })
  hl(0, "markdownHeadingDelimiter", { fg = c.blue, bg = 'NONE' })
  hl(0, "markdownHeadingRule", { fg = c.fg, bg = 'NONE', bold = true })
  hl(0, "markdownId", { fg = c.purple, bg = 'NONE' })
  hl(0, "markdownIdDeclaration", { fg = c.blue, bg = 'NONE' })
  hl(0, "markdownIdDelimiter", { fg = c.text, bg = 'NONE' })
  hl(0, "markdownLinkDelimiter", { fg = c.text, bg = 'NONE' })
  hl(0, "markdownBold", { fg = c.blue, bg = 'NONE', bold = true })
  hl(0, "markdownItalic", { fg = 'NONE', bg = 'NONE', italic = true })
  hl(0, "markdownBoldItalic", { fg = c.yellow, bg = 'NONE', bold = true, italic = true })
  hl(0, "markdownListMarker", { fg = c.blue, bg = 'NONE' })
  hl(0, "markdownOrderedListMarker", { fg = c.blue, bg = 'NONE' })
  hl(0, "markdownRule", { fg = c.accent, bg = 'NONE' })
  hl(0, "markdownUrl", { fg = c.cyan, bg = 'NONE', underline = true })
  hl(0, "markdownLinkText", { fg = c.blue, bg = 'NONE' })
  hl(0, "markdownFootnote", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownFootnoteDefinition", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownEscape", { fg = c.yellow, bg = 'NONE' })

  -- HTML
  hl(0, "htmlLink", { fg = c.link, bg = 'NONE', underline = true })
  hl(0, "htmlH1", { fg = c.cyan, bg = 'NONE', bold = true })
  hl(0, "htmlH2", { fg = c.red, bg = 'NONE', bold = true })
  hl(0, "htmlH3", { fg = c.green, bg = 'NONE', bold = true })
  hl(0, "htmlH4", { fg = c.yellow, bg = 'NONE', bold = true })
  hl(0, "htmlH5", { fg = c.purple, bg = 'NONE', bold = true })

end

return theme
