local c = require('moonlight.palette')

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()

  -- Base highlights
  hl(0, "Normal", { fg = c.fg, bg = c.bg })
  hl(0, "SignColumn", { fg = c.fg, bg = c.bg })
  hl(0, "VertSplit", { fg = c.border, bg = c.bg })
  hl(0, "NormalFloat", { fg = c.fg, bg = c.float })
  hl(0, "FloatBorder", { fg = c.border, bg = c.float })
  hl(0, "ColorColumn", { fg = 'NONE', bg = c.active })
  hl(0, "Conceal", { fg = c.disabled, bg = 'NONE' })
  hl(0, "Cursor", { fg = c.cursor, bg = 'NONE', reverse = true })
  hl(0, "CursorIM", { fg = c.cursor, bg = 'NONE', reverse = true })
  hl(0, "lCursor", { fg = c.cursor, bg = 'NONE', reverse = true })
  hl(0, "TermCursor", { fg = c.cursor, bg = 'NONE', reverse = true })
  hl(0, "TermCursorNC", { fg = c.cursor, bg = 'NONE', reverse = true })
  hl(0, "Directory", { fg = c.blue, bg = 'NONE' })
  hl(0, "DiffAdd", { fg = c.green, bg = 'NONE', reverse = true })
  hl(0, "DiffChange", { fg = c.orange, bg = 'NONE', reverse = true })
  hl(0, "DiffDelete", { fg = c.red, bg = 'NONE', reverse = true })
  hl(0, "DiffText", { fg = c.yellow, bg = 'NONE', reverse = true })
  hl(0, "EndOfBuffer", { fg = c.disabled, bg = 'NONE' })
  hl(0, "ErrorMsg", { fg = c.error, bg = 'NONE' })
  hl(0, "Folded", { fg = c.disabled, bg = 'NONE', italic = true })
  hl(0, "FoldColumn", { fg = c.text, bg = 'NONE' })
  hl(0, "IncSearch", { fg = c.bg, bg = c.yellow })
  hl(0, "LineNr", { fg = c.line_numbers, bg = 'NONE' })
  hl(0, "CursorLineNr", { fg = c.accent, bg = 'NONE' })
  hl(0, "MatchParen", { fg = c.yellow, bg = 'NONE', bold = true })
  hl(0, "ModeMsg", { fg = c.accent, bg = 'NONE' })
  hl(0, "MoreMsg", { fg = c.accent, bg = 'NONE' })
  hl(0, "MsgSeparator", { fg = c.fg, bg = c.bg })
  hl(0, "MsgArea", { link = 'Normal' })
  hl(0, "NonText", { fg = c.disabled, bg = 'NONE' })
  hl(0, "Pmenu", { fg = c.text, bg = c.contrast })
  hl(0, "PmenuSel", { fg = c.accent, bg = c.active })
  hl(0, "PmenuSbar", { fg = c.text, bg = c.contrast })
  hl(0, "PmenuThumb", { fg = c.fg, bg = c.accent })
  hl(0, "Question", { fg = c.green, bg = 'NONE' })
  hl(0, "QuickFixLine", { fg = c.bg, bg = c.yellow })
  hl(0, "qfLineNr", { fg = c.yellow, bg = 'NONE' })
  hl(0, "Search", { fg = c.bg, bg = c.yellow })
  hl(0, "SpecialKey", { fg = c.purple, bg = 'NONE' })
  hl(0, "SpellBad", { fg = c.red, bg = 'NONE', italic = true, undercurl = true })
  hl(0, "SpellCap", { fg = c.blue, bg = 'NONE', italic = true, undercurl = true })
  hl(0, "SpellLocal", { fg = c.cyan, bg = 'NONE', italic = true, undercurl = true })
  hl(0, "SpellRare", { fg = c.purple, bg = 'NONE', italic = true, undercurl = true })
  hl(0, "StatusLine", { fg = c.fg, bg = c.contrast })
  hl(0, "StatusLineNC", { fg = c.text, bg = c.disabled })
  hl(0, "StatusLineTerm", { fg = c.fg, bg = c.contrast })
  hl(0, "StatusLineTermNC", { fg = c.text, bg = c.disabled })
  hl(0, "TabLineFill", { fg = c.fg, bg = 'NONE' })
  hl(0, "TabLineSel", { fg = c.bg, bg = c.accent })
  hl(0, "TabLine", { fg = c.fg, bg = 'NONE' })
  hl(0, "Title", { fg = c.green, bg = 'NONE', bold = true })
  hl(0, "Visual", { fg = 'NONE', bg = c.selection })
  hl(0, "VisualNOS", { fg = 'NONE', bg = c.selection })
  hl(0, "WarningMsg", { fg = c.yellow, bg = 'NONE' })
  hl(0, "WildMenu", { fg = c.orange, bg = 'NONE', bold = true })
  hl(0, "CursorColumn", { fg = 'NONE', bg = c.active })
  hl(0, "CursorLine", { fg = 'NONE', bg = 'NONE' })
  hl(0, "ToolbarLine", { fg = c.fg, bg = c.bg_alt })
  hl(0, "ToolbarButton", { fg = c.fg, bg = 'NONE', bold = true })
  hl(0, "NormalMode", { fg = c.accent, bg = 'NONE', reverse = true })
  hl(0, "InsertMode", { fg = c.green, bg = 'NONE', reverse = true })
  hl(0, "ReplaceMode", { fg = c.red, bg = 'NONE', reverse = true })
  hl(0, "VisualMode", { fg = c.purple, bg = 'NONE', reverse = true })
  hl(0, "CommandMode", { fg = c.text, bg = 'NONE', reverse = true })
  hl(0, "Warnings", { fg = c.yellow, bg = 'NONE' })

  -- Health
  hl(0, "healthError", { fg = c.error, bg = 'NONE' })
  hl(0, "healthSuccess", { fg = c.green, bg = 'NONE' })
  hl(0, "healthWarning", { fg = c.yellow, bg = 'NONE' })

  -- Syntax groups
  hl(0, "Comment", { fg = c.comments, bg = 'NONE', italic = true })
  hl(0, "Constant", { fg = c.yellow, bg = 'NONE' })
  hl(0, "String", { fg = c.green, bg = 'NONE', italic = true })
  hl(0, "Character", { fg = c.orange, bg = 'NONE' })
  hl(0, "Number", { fg = c.orange, bg = 'NONE' })
  hl(0, "Boolean", { fg = c.orange, bg = 'NONE' })
  hl(0, "Float", { fg = c.orange, bg = 'NONE' })
  hl(0, "Identifier", { fg = c.text, bg = 'NONE', italic = true })
  hl(0, "Function", { fg = c.blue, bg = 'NONE', italic = true })
  hl(0, "Statement", { fg = c.pink, bg = 'NONE' })
  hl(0, "Conditional", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "Repeat", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "Label", { fg = c.purple, bg = 'NONE' })
  hl(0, "Operator", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Keyword", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "Exception", { fg = c.cyan, bg = 'NONE' })
  hl(0, "PreProc", { fg = c.purple, bg = 'NONE' })
  hl(0, "Include", { fg = c.blue, bg = 'NONE' })
  hl(0, "Define", { fg = c.pink, bg = 'NONE' })
  hl(0, "Macro", { fg = c.cyan, bg = 'NONE' })
  hl(0, "PreCondit", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Type", { fg = c.purple, bg = 'NONE' })
  hl(0, "StorageClass", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Structure", { fg = c.purple, bg = 'NONE' })
  hl(0, "Typedef", { fg = c.red, bg = 'NONE' })
  hl(0, "Special", { fg = c.red, bg = 'NONE' })
  hl(0, "SpecialChar", { fg = c.pink, bg = 'NONE' })
  hl(0, "Tag", { fg = c.red, bg = 'NONE' })
  hl(0, "Delimiter", { fg = c.cyan, bg = 'NONE' })
  hl(0, "SpecialComment", { fg = c.text, bg = 'NONE' })
  hl(0, "Debug", { fg = c.red, bg = 'NONE' })
  hl(0, "Underlined", { fg = c.link, bg = 'NONE', underline = true })
  hl(0, "Ignore", { fg = c.disabled, bg = 'NONE' })
  hl(0, "Error", { fg = c.error, bg = 'NONE', bold = true, underline = true })
  hl(0, "Todo", { fg = c.yellow, bg = 'NONE', bold = true, italic = true })

  -- Markdown
  hl(0, "markdownBlockquote", { fg = c.green, bg = 'NONE' })
  hl(0, "markdownCode", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownCodeBlock", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownCodeDelimiter", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownH1", { fg = c.cyan, bg = 'NONE', bold = true })
  hl(0, "markdownH2", { fg = c.red, bg = 'NONE', bold = true })
  hl(0, "markdownH3", { fg = c.green, bg = 'NONE', bold = true })
  hl(0, "markdownH4", { fg = c.cyan, bg = 'NONE' })
  hl(0, "markdownH5", { fg = c.red, bg = 'NONE' })
  hl(0, "markdownH6", { fg = c.green, bg = 'NONE' })
  hl(0, "markdownHeadingDelimiter", { fg = c.blue, bg = 'NONE' })
  hl(0, "markdownHeadingRule", { fg = c.fg, bg = 'NONE', bold = true })
  hl(0, "markdownId", { fg = c.purple, bg = 'NONE' })
  hl(0, "markdownIdDeclaration", { fg = c.blue, bg = 'NONE' })
  hl(0, "markdownIdDelimiter", { fg = c.text, bg = 'NONE' })
  hl(0, "markdownLinkDelimiter", { fg = c.text, bg = 'NONE' })
  hl(0, "markdownBold", { fg = c.blue, bg = 'NONE', bold = true })
  hl(0, "markdownItalic", { fg = 'NONE', bg = 'NONE', italic = true })
  hl(0, "markdownBoldItalic", { fg = c.yellow, bg = 'NONE', bold = true, italic = true })
  hl(0, "markdownListMarker", { fg = c.blue, bg = 'NONE' })
  hl(0, "markdownOrderedListMarker", { fg = c.blue, bg = 'NONE' })
  hl(0, "markdownRule", { fg = c.accent, bg = 'NONE' })
  hl(0, "markdownUrl", { fg = c.cyan, bg = 'NONE', underline = true })
  hl(0, "markdownLinkText", { fg = c.blue, bg = 'NONE' })
  hl(0, "markdownFootnote", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownFootnoteDefinition", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownEscape", { fg = c.yellow, bg = 'NONE' })

  -- HTML
  hl(0, "htmlLink", { fg = c.link, bg = 'NONE', underline = true })
  hl(0, "htmlH1", { fg = c.cyan, bg = 'NONE', bold = true })
  hl(0, "htmlH2", { fg = c.red, bg = 'NONE', bold = true })
  hl(0, "htmlH3", { fg = c.green, bg = 'NONE', bold = true })
  hl(0, "htmlH4", { fg = c.yellow, bg = 'NONE', bold = true })
  hl(0, "htmlH5", { fg = c.purple, bg = 'NONE', bold = true })

  -- TreeSitter (legacy)
  hl(0, "TSAnnotation", { fg = c.red, bg = 'NONE' })
  hl(0, "TSAttribute", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSBoolean", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSCharacter", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSComment", { fg = c.comments, bg = 'NONE', italic = true })
  hl(0, "TSConditional", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "TSConstant", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSConstBuiltin", { fg = c.blue, bg = 'NONE' })
  hl(0, "TSConstMacro", { fg = c.blue, bg = 'NONE' })
  hl(0, "TSConstructor", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSError", { fg = c.error, bg = 'NONE' })
  hl(0, "TSException", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSField", { fg = c.text, bg = 'NONE' })
  hl(0, "TSFloat", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSFunction", { fg = c.blue, bg = 'NONE', italic = true })
  hl(0, "TSFuncBuiltin", { fg = c.cyan, bg = 'NONE', italic = true })
  hl(0, "TSFuncMacro", { fg = c.blue, bg = 'NONE' })
  hl(0, "TSInclude", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSKeyword", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "TSKeywordFunction", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "TSLabel", { fg = c.red, bg = 'NONE' })
  hl(0, "TSMethod", { fg = c.blue, bg = 'NONE', italic = true })
  hl(0, "TSNamespace", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSNumber", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSOperator", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSParameter", { fg = c.paleblue, bg = 'NONE' })
  hl(0, "TSParameterReference", { fg = c.paleblue, bg = 'NONE' })
  hl(0, "TSProperty", { fg = c.paleblue, bg = 'NONE' })
  hl(0, "TSPunctDelimiter", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSPunctBracket", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSPunctSpecial", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSRepeat", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "TSString", { fg = c.green, bg = 'NONE', italic = true })
  hl(0, "TSStringRegex", { fg = c.blue, bg = 'NONE' })
  hl(0, "TSStringEscape", { fg = c.disabled, bg = 'NONE' })
  hl(0, "TSSymbol", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSTag", { fg = c.red, bg = 'NONE' })
  hl(0, "TSTagDelimiter", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSText", { fg = c.text, bg = 'NONE' })
  hl(0, "TSEmphasis", { fg = c.paleblue, bg = 'NONE', italic = true })
  hl(0, "TSUnderline", { fg = c.fg, bg = 'NONE', underline = true })
  hl(0, "TSStrike", { fg = c.fg, bg = 'NONE', strikethrough = true })
  hl(0, "TSTitle", { fg = c.paleblue, bg = 'NONE', bold = true })
  hl(0, "TSLiteral", { fg = c.fg, bg = 'NONE' })
  hl(0, "TSURI", { fg = c.link, bg = 'NONE', underline = true })
  hl(0, "TSType", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSTypeBuiltin", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSVariable", { fg = c.text, bg = 'NONE', italic = true })
  hl(0, "TSVariableBuiltin", { fg = c.text, bg = 'NONE', italic = true })

  -- TreeSitter (modern @ syntax)
  hl(0, "@annotation", { fg = c.red, bg = 'NONE' })
  hl(0, "@attribute", { fg = c.yellow, bg = 'NONE' })
  hl(0, "@boolean", { link = 'Boolean' })
  hl(0, "@character", { link = 'Character' })
  hl(0, "@character.special", { link = 'SpecialChar' })
  hl(0, "@comment", { link = 'Comment' })
  hl(0, "@comment.documentation", { link = 'Comment' })
  hl(0, "@conditional", { link = 'Conditional' })
  hl(0, "@conditional.ternary", { link = 'Conditional' })
  hl(0, "@constant", { link = 'Constant' })
  hl(0, "@constant.builtin", { fg = c.blue, bg = 'NONE' })
  hl(0, "@constant.macro", { fg = c.blue, bg = 'NONE' })
  hl(0, "@constructor", { fg = c.purple, bg = 'NONE' })
  hl(0, "@debug", { link = 'Debug' })
  hl(0, "@define", { link = 'Define' })
  hl(0, "@error", { link = 'Error' })
  hl(0, "@exception", { fg = c.yellow, bg = 'NONE' })
  hl(0, "@field", { fg = c.text, bg = 'NONE' })
  hl(0, "@float", { link = 'Float' })
  hl(0, "@function", { link = 'Function' })
  hl(0, "@function.builtin", { fg = c.cyan, bg = 'NONE', italic = true })
  hl(0, "@function.call", { link = '@function' })
  hl(0, "@function.macro", { fg = c.blue, bg = 'NONE' })
  hl(0, "@include", { fg = c.cyan, bg = 'NONE' })
  hl(0, "@keyword", { link = 'Keyword' })
  hl(0, "@keyword.coroutine", { link = 'Keyword' })
  hl(0, "@keyword.function", { link = 'Keyword' })
  hl(0, "@keyword.operator", { fg = c.purple, bg = 'NONE', italic = true })
  hl(0, "@keyword.return", { link = 'Keyword' })
  hl(0, "@label", { fg = c.red, bg = 'NONE' })
  hl(0, "@method", { fg = c.blue, bg = 'NONE', italic = true })
  hl(0, "@method.call", { link = '@method' })
  hl(0, "@namespace", { fg = c.yellow, bg = 'NONE' })
  hl(0, "@number", { link = 'Number' })
  hl(0, "@operator", { link = 'Operator' })
  hl(0, "@parameter", { fg = c.paleblue, bg = 'NONE' })
  hl(0, "@preproc", { link = 'PreProc' })
  hl(0, "@property", { fg = c.paleblue, bg = 'NONE' })
  hl(0, "@punctuation.bracket", { fg = c.cyan, bg = 'NONE' })
  hl(0, "@punctuation.delimiter", { link = 'Delimiter' })
  hl(0, "@punctuation.special", { fg = c.cyan, bg = 'NONE' })
  hl(0, "@repeat", { link = 'Repeat' })
  hl(0, "@storageclass", { link = 'StorageClass' })
  hl(0, "@string", { link = 'String' })
  hl(0, "@string.documentation", { fg = c.paleblue, bg = 'NONE' })
  hl(0, "@string.escape", { fg = c.disabled, bg = 'NONE' })
  hl(0, "@string.regex", { fg = c.blue, bg = 'NONE' })
  hl(0, "@string.special", { fg = c.green, bg = 'NONE' })
  hl(0, "@symbol", { fg = c.yellow, bg = 'NONE' })
  hl(0, "@tag", { link = 'Tag' })
  hl(0, "@tag.attribute", { fg = c.purple, bg = 'NONE' })
  hl(0, "@tag.delimiter", { fg = c.yellow, bg = 'NONE' })
  hl(0, "@text", { fg = c.text, bg = 'NONE' })
  hl(0, "@text.strong", { fg = c.blue, bg = 'NONE', bold = true })
  hl(0, "@text.emphasis", { fg = c.paleblue, bg = 'NONE', italic = true })
  hl(0, "@text.underline", { fg = c.fg, bg = 'NONE', underline = true })
  hl(0, "@text.strike", { fg = c.fg, bg = 'NONE', strikethrough = true })
  hl(0, "@text.title", { fg = c.paleblue, bg = 'NONE', bold = true })
  hl(0, "@text.literal", { fg = c.fg, bg = 'NONE' })
  hl(0, "@text.quote", { fg = c.yellow, bg = 'NONE' })
  hl(0, "@text.uri", { fg = c.link, bg = 'NONE', underline = true })
  hl(0, "@text.math", { fg = c.pink, bg = 'NONE' })
  hl(0, "@text.reference", { fg = c.yellow, bg = 'NONE' })
  hl(0, "@text.todo", { link = 'Todo' })
  hl(0, "@text.note", { link = 'Todo' })
  hl(0, "@text.warning", { link = 'WarningMsg' })
  hl(0, "@text.danger", { link = 'ErrorMsg' })
  hl(0, "@text.diff.add", { link = 'DiffAdd' })
  hl(0, "@text.diff.delete", { link = 'DiffDelete' })
  hl(0, "@type", { link = 'Type' })
  hl(0, "@type.builtin", { fg = c.purple, bg = 'NONE' })
  hl(0, "@type.definition", { link = 'Type' })
  hl(0, "@type.qualifier", { link = 'Type' })
  hl(0, "@variable", { fg = c.text, bg = 'NONE', italic = true })
  hl(0, "@variable.builtin", { link = '@variable' })

  -- Rainbow Delimiters
  hl(0, "RainbowDelimiterRed", { fg = c.red, bg = 'NONE' })
  hl(0, "RainbowDelimiterYellow", { fg = c.yellow, bg = 'NONE' })
  hl(0, "RainbowDelimiterBlue", { fg = c.blue, bg = 'NONE' })
  hl(0, "RainbowDelimiterOrange", { fg = c.orange, bg = 'NONE' })
  hl(0, "RainbowDelimiterGreen", { fg = c.green, bg = 'NONE' })
  hl(0, "RainbowDelimiterViolet", { fg = c.purple, bg = 'NONE' })
  hl(0, "RainbowDelimiterCyan", { fg = c.cyan, bg = 'NONE' })

  -- LSP Diagnostics
  hl(0, "DiagnosticError", { fg = c.error, bg = 'NONE' })
  hl(0, "DiagnosticWarn", { fg = c.warning, bg = 'NONE' })
  hl(0, "DiagnosticInfo", { fg = c.info, bg = 'NONE' })
  hl(0, "DiagnosticHint", { fg = c.hint, bg = 'NONE' })
  hl(0, "DiagnosticOk", { fg = c.green, bg = 'NONE' })
  
  hl(0, "DiagnosticSignError", { fg = c.error, bg = 'NONE' })
  hl(0, "DiagnosticSignWarn", { fg = c.warning, bg = 'NONE' })
  hl(0, "DiagnosticSignInfo", { fg = c.info, bg = 'NONE' })
  hl(0, "DiagnosticSignHint", { fg = c.hint, bg = 'NONE' })
  hl(0, "DiagnosticSignOk", { fg = c.green, bg = 'NONE' })
  
  hl(0, "DiagnosticVirtualTextError", { fg = c.error, bg = 'NONE' })
  hl(0, "DiagnosticVirtualTextWarn", { fg = c.warning, bg = 'NONE' })
  hl(0, "DiagnosticVirtualTextInfo", { fg = c.info, bg = 'NONE' })
  hl(0, "DiagnosticVirtualTextHint", { fg = c.hint, bg = 'NONE' })
  hl(0, "DiagnosticVirtualTextOk", { fg = c.green, bg = 'NONE' })
  
  hl(0, "DiagnosticUnderlineError", { sp = c.error, undercurl = true })
  hl(0, "DiagnosticUnderlineWarn", { sp = c.warning, undercurl = true })
  hl(0, "DiagnosticUnderlineInfo", { sp = c.info, undercurl = true })
  hl(0, "DiagnosticUnderlineHint", { sp = c.hint, undercurl = true })
  hl(0, "DiagnosticUnderlineOk", { sp = c.green, undercurl = true })
  
  hl(0, "DiagnosticFloatingError", { fg = c.error, bg = 'NONE' })
  hl(0, "DiagnosticFloatingWarn", { fg = c.warning, bg = 'NONE' })
  hl(0, "DiagnosticFloatingInfo", { fg = c.info, bg = 'NONE' })
  hl(0, "DiagnosticFloatingHint", { fg = c.hint, bg = 'NONE' })
  hl(0, "DiagnosticFloatingOk", { fg = c.green, bg = 'NONE' })

  -- LSP References
  hl(0, "LspReferenceText", { bg = c.selection })
  hl(0, "LspReferenceRead", { bg = c.selection })
  hl(0, "LspReferenceWrite", { bg = c.selection })

  -- LSP Signature Help
  hl(0, "LspSignatureActiveParameter", { fg = c.yellow, bg = 'NONE', bold = true })

  -- LSP Code Lens
  hl(0, "LspCodeLens", { fg = c.comments, bg = 'NONE', italic = true })
  hl(0, "LspCodeLensSeparator", { fg = c.disabled, bg = 'NONE' })

  -- Git Signs
  hl(0, "GitSignsAdd", { fg = c.green, bg = 'NONE' })
  hl(0, "GitSignsChange", { fg = c.yellow, bg = 'NONE' })
  hl(0, "GitSignsDelete", { fg = c.red, bg = 'NONE' })
  hl(0, "GitSignsAddNr", { fg = c.green, bg = 'NONE' })
  hl(0, "GitSignsChangeNr", { fg = c.yellow, bg = 'NONE' })
  hl(0, "GitSignsDeleteNr", { fg = c.red, bg = 'NONE' })
  hl(0, "GitSignsAddLn", { fg = c.green, bg = 'NONE' })
  hl(0, "GitSignsChangeLn", { fg = c.yellow, bg = 'NONE' })
  hl(0, "GitSignsDeleteLn", { fg = c.red, bg = 'NONE' })
  hl(0, "GitSignsAddInline", { fg = c.green, bg = 'NONE' })
  hl(0, "GitSignsChangeInline", { fg = c.yellow, bg = 'NONE' })
  hl(0, "GitSignsDeleteInline", { fg = c.red, bg = 'NONE' })
  hl(0, "GitSignsCurrentLineBlame", { fg = c.comments, bg = 'NONE', italic = true })

  -- Git (general)
  hl(0, "gitcommitComment", { fg = c.comments, bg = 'NONE', italic = true })
  hl(0, "gitcommitUnmerged", { fg = c.green, bg = 'NONE', bold = true })
  hl(0, "gitcommitOnBranch", { fg = c.text, bg = 'NONE', bold = true })
  hl(0, "gitcommitBranch", { fg = c.purple, bg = 'NONE', bold = true })
  hl(0, "gitcommitDiscardedType", { fg = c.red, bg = 'NONE' })
  hl(0, "gitcommitSelectedType", { fg = c.green, bg = 'NONE' })
  hl(0, "gitcommitHeader", { fg = c.text, bg = 'NONE' })
  hl(0, "gitcommitUntrackedFile", { fg = c.cyan, bg = 'NONE' })
  hl(0, "gitcommitDiscardedFile", { fg = c.red, bg = 'NONE' })
  hl(0, "gitcommitSelectedFile", { fg = c.green, bg = 'NONE' })
  hl(0, "gitcommitUnmergedFile", { fg = c.yellow, bg = 'NONE', bold = true })
  hl(0, "gitcommitFile", { fg = c.fg, bg = 'NONE', bold = true })
  hl(0, "gitcommitSummary", { fg = c.fg, bg = 'NONE' })
  hl(0, "gitcommitOverflow", { fg = c.red, bg = 'NONE' })

  -- Telescope
  hl(0, "TelescopeBorder", { fg = c.border, bg = c.float })
  hl(0, "TelescopePromptBorder", { fg = c.cyan, bg = c.float })
  hl(0, "TelescopeResultsBorder", { fg = c.purple, bg = c.float })
  hl(0, "TelescopePreviewBorder", { fg = c.green, bg = c.float })
  hl(0, "TelescopePromptNormal", { fg = c.fg, bg = c.float })
  hl(0, "TelescopeResultsNormal", { fg = c.fg, bg = c.float })
  hl(0, "TelescopePreviewNormal", { fg = c.fg, bg = c.float })
  hl(0, "TelescopePromptPrefix", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TelescopeSelection", { fg = c.purple, bg = c.selection })
  hl(0, "TelescopeSelectionCaret", { fg = c.purple, bg = c.selection })
  hl(0, "TelescopeMatching", { fg = c.cyan, bg = 'NONE', bold = true })
  hl(0, "TelescopePromptTitle", { fg = c.cyan, bg = 'NONE', bold = true })
  hl(0, "TelescopeResultsTitle", { fg = c.purple, bg = 'NONE', bold = true })
  hl(0, "TelescopePreviewTitle", { fg = c.green, bg = 'NONE', bold = true })

  -- WhichKey
  hl(0, "WhichKey", { fg = c.accent, bg = 'NONE', bold = true })
  hl(0, "WhichKeyGroup", { fg = c.text, bg = 'NONE' })
  hl(0, "WhichKeyDesc", { fg = c.blue, bg = 'NONE', italic = true })
  hl(0, "WhichKeySeperator", { fg = c.fg, bg = 'NONE' })
  hl(0, "WhichKeySeparator", { fg = c.fg, bg = 'NONE' })
  hl(0, "WhichKeyFloat", { fg = 'NONE', bg = c.float })
  hl(0, "WhichKeyFloating", { fg = 'NONE', bg = c.float })
  hl(0, "WhichKeyValue", { fg = c.green, bg = 'NONE' })

end

return theme
